Update query example schema-type.md
elysiajs/documentation pull request #369
Opened 2024-08-17 15:28 UTC by JoeSlain

The example for the query schema type is printed as an object, shouldn't it be shown as a url like the very fist example of the page ?
Like the URL column of this picture: 
![image](https://github.com/user-attachments/assets/be1bf3ff-95c6-4773-8124-f498580af9af)

Also added a valid example of using mandatory name along with optional alias.

2024-08-17 20:17 UTC, bogeychan requested changes
Yeah, it looks like a copy-and-paste issue. Thanks for catching that!

2024-08-17 20:17 UTC, bogeychan commented on docs/validation/schema-type.md
> +| /?name=1 | ❌ |
This line should be `| /?name=1 | ✅ |`

2024-08-17 20:17 UTC, bogeychan commented on docs/validation/schema-type.md
>  | `undefined` | ❌ |
Instead of `undefined` use `/` please

2024-08-17 21:45 UTC, JoeSlain commented
> Yeah, it looks like a copy-and-paste issue. Thanks for catching that!

Done (:

2024-08-18 13:28 UTC, bogeychan approved these changes
LGTM, ty for your contribution!

2024-08-18 13:28 UTC, merged